name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable pnpm 10.2.1 via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.2.1 --activate
      - name: Install Dependencies & Build
        run: |
          pnpm install
          pnpm --filter functions install
          pnpm --filter functions run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
